### ISSUE TITLE
Search blocks and create brush from list of markers

### ISSUE THREAD

**Issue by gabrielkg** [plantinformatics/pretzel#112]
Add input text field to View tab, which accepts one or more feature names. Following this:

1) List blocks which contain one or more of the listed features below, indicating how many of the listed features are in the block, with ability to immediately load to the view.

2) If the features are present in any loaded block: if a single marker, add a tick with its name indicated; if multiple, generate a brush defined by the extremes and add ticks with their names.

**Comment by Don-Isdale** [comment]
#112 is implemented, principally in 
db005ce, df106ee backend/common/models/feature.js 
2bb6ae1..f14fedb :
  components/panel/feature-list
  components/goto-feature-list
