### ISSUE TITLE
Deleting parent with child loaded does not always remove from Displayed Data list

### ISSUE THREAD

**Issue by gabrielkg** [plantinformatics/pretzel#114]
This appears to affect datasets uploaded by users on plantinformatics.io. When a parent is defined for a dataset, and a block loaded which results in the automatic loading of the parent, deleting the parent does not completely delete the datasets - they remain in the Displayed Data list in the View tab and cannot be re-added because the + button is not available in the Explorer.

**Comment by Don-Isdale** [comment]
In fd26321 I fixed an issue which fits the description except it was reproduced with split (open) axes, and not observed with regular axes.
So this may be fixed.

Note that 'delete' in the above comment means unview (remove from the view), not remove from the database.
