### ISSUE TITLE
API testing of paths requests - paths-aggr

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#137]
initial focus would be on confirming that the functions return a result when expected, and in the correct form,  then we can design up some small test cases which check the results returned, e.g. checking that feature location filtering is correct, and that multiple instances of a feature in a block are handled.
We can also use resources/public_maps/ and pretzel-data as test data, but preferably without adding large test results to the source repo, e.g. the request can be designed to have a small expected result, using location filtering.

**Comment by kieranongh** [comment]
Is there a testing framework we're currently using?
