### ISSUE TITLE
Cannot brush bottom half of axis when stacked

### ISSUE THREAD

**Issue by gabrielkg** [plantinformatics/pretzel#174]
To reproduce:
- Stack any two axes
- Brush axis so brush spans most of the length of the axis

Result:
- Features in bottom half of axis are not selected or displayed in tables on right

See attached image.
![image](https://user-images.githubusercontent.com/20571319/76377659-9214ad80-639f-11ea-95e5-21ce497961de.png)

**Comment by Don-Isdale** [comment]
Addressed by ce121bc
