### ISSUE TITLE
Paths disappearing

### ISSUE THREAD

**Issue by gabrielkg** [plantinformatics/pretzel#179]
To reproduce:

1. Load IWGSC HC genes vs barley genes
2. Zoom in on both axes
3. Click reset zooms

Only the zoomed region paths are shown, and zooming in/out, rearranging axes etc does not bring the other paths back. See attached image. 
![image](https://user-images.githubusercontent.com/20571319/80554756-7ded4400-8a11-11ea-962b-143b1f61ad61.png)

**Comment by Don-Isdale** [comment]
OK for directs, still occurring for aliases

**Comment by gabrielkg** [comment]
Still happening in 268c51c following the example described in the initial issue.

**Comment by Don-Isdale** [comment]
was able to fix most of the #179 issue with a minor change (8a1841e), but chasing an intermittent / timing occurrence of it.
- [ ] there is an additional point :  updating paths when zoom out for a block added beside a zoomed-in axis
