### ISSUE TITLE
dataset upload over https may not complete

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#185]
Since switching the sites to https, uploads have mostly failed.
Small uploads may be OK, and possibly CSV.
The upload appears to progress to 100%, then displays 'updating database' and hangs.
Earlier it appeared to time-out after a minute (which is the proxy buffer timeout), with :
  POST https://dev.plantinformatics.io/api/Datasets/upload 504 (Gateway Time-out)
Refreshing the app in another tab showed the upload had completed OK (current timestamps in the meta).
If the upload is repeated, it gives 'duplicate dataset id' error, and that occurred straight away, no hang-up.
Other error codes have been noted.
Testing with curl upload gives a similar result.

**Comment by scientistanton** [comment]
I may be experiencing a version of this issue. I am trying to upload a map as a csv. Nothing appears to be happening. If I look in the console I see the following error: "Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)". I hope this is helpful at that this is the correct issue to be commenting upon. If not I can raise a new one.

**Comment by Don-Isdale** [comment]
Thanks - yes that is helpful.   We aren't currently seeing that issue on the dev servers, which are using https.
I'll check the server and proxy logs for the site you are uploading to - I guess it is  plantinformatics.io, let me know if not.
It's possible for varying network configurations to be a factor in this, so it is useful to get feedback from different locations.
I'll report back;  thanks,

**Comment by Don-Isdale** [comment]
The server log has : Unhandled error for request POST /api/datasets: ValidationError: The Dataset instance is not valid. Details: name can't be blank (value: "").
so first thing to check is the dataset name input field in the upload panel.
This is not yet very user-friendly (we are just shifting to focus on removing some pot-holes like this), and it should warn you if the field is empty (not sure if that happens); and we should feed the above message back to the user console ...
dataset input field also needs to be unique, and I think that may not be reported back adequately yet

**Comment by scientistanton** [comment]
Thank you very much. That has worked. The dataset is now in there as Maringa_Spica

**Comment by Don-Isdale** [comment]
That's great !
Thanks for the report - that helps us to focus on the friction points which we can smooth out.
