### ISSUE TITLE
axis flip issues

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#202]
- [x] axis flip causing mousewheel-zoom to not work
done in feature/move_axisShowExtend 3b44d42
- [x] axis flip does not update brush position / value / selected features	(e85c6bc3. 8b957196)
- [x] axis flip clears tracks shown in split axis

**Comment by gabrielkg** [comment]
Still present in 321bb83.

**Comment by gabrielkg** [comment]
Fixed in 8b95719.
