### ISSUE TITLE
Frameworks versions upgrade

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#210]
Bring all (frontend) frameworks and libraries forward to the current version in parallel :
- [x] Ember (ember-cli, ember-data, etc)
- - [x] ember-cli-update --run-codemods  (37de2ac0)
- - [x] update versions using ncu -u;   first round of changes to adapt to updated versions. (b95f6c46)
- - [x] use adapter headers() to configure Authorization token (b6987465)
- - [x] use primaryServer.getDatasets() to get result in datasetsBlocks; update task .value -> ._result (6cf64609)
- - [x] apply ember-3x-codemods : 
- - - [x] cp-volatile  2cd8558d.  split filter out of CP to avoid using .property() : 68a43fc6
- - - [x] fpe-computed 5864ad85
- - - [x] fpe-observes 384d96ac
- - - [x] fpe-on	     7bdd502f
- - - [x] jquery-apis :  change uses of this.$() to this.element / querySelectorAll, as per https://github.com/ember-codemods/ember-3x-codemods/tree/master/transforms/jquery-apis  (1eddb485)
- - [x] wrap style returned by CPs with htmlSafe(CSS.escape( ))  (e80071d9)
- - [x] solve name clash caused by ember-modules-codemod; ignore sendAction deprecation for now. (1340bc73)
- - [x] rename Dataset and Block .meta to ._meta to avoid clash with Ember Data .meta (02df5bd1)
- - [x] rename .layout to avoid clash with Component reserved attribute;  this got the dataset explorer working (76dca9fc)
- - [x] drop .isVisible; add glyphicons-halflings (0f541fdc); this showed the icons in the dataset explorer 
- - [x] axis brush, get features
these 2 are done ( 9dd1c79e, and probably an axes-1d.hbs change).
- - [x] show paths
- - [x] the right-panel tabs work but the left-panel tabs and explorer tabs don't
fixed via changing nav-tabs to BsTab (from ember-bootstrap) (left-panel top tabs done in 7189ba6f; explorer tabs split out as a sub-item )
- - - [x] vertical scrolling in the left panel is not working after those changes
done in 9a6e297e
- - - [x] similar for the tabs in the dataset explorer
done in 82202c80, with a remaining issue :
- - - - [x] changing tab does not clear the active flag on the first tab.
fixed in 897a637a. also set the initial tab : 2df548b8 
- - [x] axis menu
- - - [x] Convert axis title menu from $.popover() to hbs (ae114cf5)
- - - [x] add Close button (422b9abf)
- - - [x] connection actions to buttons (037cd694)
- - - [x] clear menuAxis so that next click will open menu again (3af6e133)
- - - [x] change target of popover (0d7b63fc)
- - - [x] close menu when axis is removed	(f2896985)
- - - [x] use axis id so that actions apply to the clicked menu (a2287cc3)
- - - [x] block text : replace demo text with real text (064fffc9)
- - - [x] add the block-remove-from-view buttons (839d3f93).
- - - [x] add block list click -> menu (e8af64ee)
- - - [x] reposition menu when another axis is clicked (possibly close & re-open) (e8af64ee)
- - - [x]  close menu when one of the action buttons is clicked (08133f07) 
- - - [x] indicate sensitivity (hover) using italic / bold instead of opacity
done in c2876a80, 7c0f8656
- - - [x] margin around X needed when short text.   set a minimum width	(86c25356)

- - [x] zooming from charts down to tracks / features - tracks received but not shown
fixed in f8c81b18

- - [x] convert jQuery().popover() dialogs to hbs :
enabled access to jQuery().popover(), so converting to hbs is not required. (c5a1d79f)
- - - axis-tracks.js : configureHorizTickHover()
- - - draw-map.js : configureHorizTickHover()
- - - flow-controls.js : configurejQueryTooltip()
- - - hover.js : configureHorizTickHover()

- - [x] no paths, because of block.axis.
Dropped dependencies on block.axis (35967357).
fix issue in lookup of axis of block (f8c81b18)
- - [x] addNewDatasource() uses jQuery.modal() - change to hbs
done :  f5117533, 83b4b09a, and added error display :  3bafd517

- various exception fixes
- - 7cf4595d  handle un-viewed block when positioning block tspan in axis title
- - 480e55f7  handle path render after block containing one end of the path is un-viewed.
- - 97d2178d  change lookup of blockAdj.blockAdjId to solve undefined when un-viewing a block.

- [x] performance improvements
- - [x]  pathPosition (43dc42b7, 5ab57b2c)
- - [x] features.length debounce
(9918cafd)
- - [x] axisTitle
- - [x]  paths{,Aliases}Result length debounce
- - [x] use the slider-adjustable times in axis-position (64b1e1d8)

- [x] dataset explorer :  button actions : enable access to dataset actions -delete, make-public
done in 48e5ec2d.
- [x] update axis horizontal position after re-opening the right panel	(9522c33a)

- [x] adjust threshold so that result which covers axis is preferred if the bin size is reasonable
done in 880ddd82 : incorporate binSize comparison into .coverage sort
- [x] check that featuresCounts chart request is sent after zooming stops, i.e. that the whole area displayed has a chart

- [x] click twice on a left panel tab (Explorer, View, Feature Search, Upload) cause the tabs to disappear	(084a768e)

- [x] sometimes outside paths (ends of chromosome) are not added after zoom out.  add an update.
(made a change in 01a45666, reverted that in 1532a276,)  still current
done in 4395dc2f.

- [x] block remove-from-view button in menu  (736fc0df)

- [x] delete and re-add : no paths until some action (update issue)		(4e583ac)

- [x] graph width resizer : hover only needs a colour change; currently increases text icon size, shows additional icon. (a93b59a2)

- [x] investigate why axis delete is slow	(b6a7f91a, faf10eff, d4df0f90, e8281ce2, 2b0a93b1, 13d6c500 , b21f847b) 
- - [x] request features for last-added split axis when zoomed in  (5020ca73)

- [x] update paths positions after split axis open/close	(6e3d02b1, and 001e660c, and cc4bb11c, and 80607876)

- [x] not building on dev.    committed and pushed :  https://github.com/plantinformatics/ember-cli-multi-store-service/commit/68158baba
- [x]  server-coloured border around the server tabs  (f014a78c)
- - [x] colour and layout of the server tabs in the explorer, and active highlight	(d01838a5)

- [x] display of table for upload csv	(6cdb7049)
- - [x] Update datasets shown in explorer, after upload.	(f1cf97f8)

- [x] The counter showing number of features loaded seems to be wrong - often it is 0 or 1	(3165147f)

- [x]  zooming in then loading an axis along side will only draw the paths at the zoomed in level and not request when zooming out	(2f221c4d)
- [x] enable refresh datasets when user has not changed tab (just primary)	(23d1f70a)

- [x] Investigate timing of drawing features after resetting zooms - seems to currently wait before all features are drawn, then switch to charts	(c8100508)

- [x] Fix exports undefined in docker build	(interval-overlap in Dockerfile c4f2e225)
- [x] routing issue after login : goes to index route instead of mapview	(ea25abe2)
- [ ] #217 login sometimes bounces back to login page
[CURRENT_FOCUS]

- [x] babel, brocolli, 
- [x] possibly transition away from bower and build dependencies only through npm
in b95f6c46 a number of dependencies were removed from bower.json. Others can be moved to npm as needed.
- [ ] d3 (could be done separately, depending on time and complexity)
- [ ]  Bootstrap : if possible remain with v3 in the first pass, as there will be a number of scattered changes to update to v4.
- - [x]  roll back to Bootstrap 3 (6b313e72)

Backend versions can be updated at the same time, or possibly separately depending on time
- node / npm
- express / loopback

**Comment by gabrielkg** [comment]
Closed off with the release of v2.3.0.
