### ISSUE TITLE
update axis title angle when resize

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#22]
update axis title angle when resize; it currently just sets the angle of maps when added; 
-	axis title rotation : apply to all together, in a transition
could change svgContainer translation y (same transition) instead of using a sudden css padding-top (svg.verticalTitle {  padding-top: 79px; })
from notes, 2017Sep 24

**Comment by gabrielkg** [comment]
Still present in develop commit c6ea70d.

**Comment by gabrielkg** [comment]
Fixed.
