### ISSUE TITLE
Metadata editing no longer works

### ISSUE THREAD

**Issue by gabrielkg** [plantinformatics/pretzel#222]
Tested on 48f873dc:

- [x] When editing metadata for a dataset (by either clicking the "Edit" button in right panel or directly in the metadata box), focus is lost after every character typed (need to click into the text box again)	(52a45fb9, c29cf09c)
- [x] After saving the change, it appears applied to all datasets (they all have an extra field with the value just defined)	(be584c12)
- [x] Change is not saved to backend	(be584c12)

**Comment by Don-Isdale** [comment]
Completed, will be included in 2.3.2
