### ISSUE TITLE
Selections and defining intervals

### ISSUE THREAD

**Issue by gabrielkg** [plantinformatics/pretzel#223]
Developing the concept of selections and intervals.

- [x] 1. Clicking a feature, with left click, in split axis switches focus to Feature Search tab in left panel and adds selected (clicked) to feature search list (which adds triangle). Clicking feature again removes from list (and removes triangle).

![image](https://user-images.githubusercontent.com/20571319/106707860-07d3d880-6646-11eb-9f9a-db108628277c.png)

- [x] 2. Left clicking triangle adds label with feature name next to triangle, clicking triangle again removes label.

![image](https://user-images.githubusercontent.com/20571319/106708274-af510b00-6646-11eb-8538-e9be9fac09f8.png)

- [x] 3. Shift+ left click triangles on an axis draws a line across the top of the outermost triangles

**Comment by Don-Isdale** [comment]
draft data design :
service/data/selected :
-  features		# features not feature names.  just clicked features, not all the search results
-  labelledFeatures	# triangles which were clicked

Assumptions :
- if the user modifies the search list, then clicks search, then the triangles will be just the search results.

Questions :
- if the user modifies the search list, then clicks search, should labelledFeatures not in the search results still be labelled ?

**Comment by gabrielkg** [comment]
If the user modifies the search list and searches, then previously labelled features should no longer be labelled. This is because the action of clicking a feature adds it to the search list, and clicking again unlists it, so removing from list should also unlabel.

**Comment by Don-Isdale** [comment]
Design items :
1. Clicking a feature, with left click, in split axis switches focus to Feature Search tab in left panel and adds selected (clicked) to feature search list (which adds triangle). Clicking feature again removes from list (and removes triangle).
- a.  [done. 4H] 2 arrays of features ( clicked features and labelled features), with click to toggle array membership
- b.  [1H] show triangles for the features in the array : clicked features

2. Left clicking triangle adds label with feature name next to triangle, clicking triangle again removes label.
- a. [1H] click -> toggle feature in array : labelled features
- b. [2H] show labels for the features in the array : labelled features

3. Shift+ left click triangles on an axis draws a line across the top of the outermost triangles
- a. [1H] determine extent of clicked features
- b. [1H] draw path across extent, near the base of the triangles

**Comment by Don-Isdale** [comment]
- [ ] switch off hover text on axis tracks and triangles
- - [ ]  show that text in a component in top-right of the graph space (adjacent the right-panel). this component can be moved later as needed.

**Comment by gabrielkg** [comment]
![image](https://user-images.githubusercontent.com/20571319/107452939-2c780500-6b9e-11eb-82e7-e5beff0d3705.png)
