### ISSUE TITLE
width calculation / resize

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#23]
* minimising left panel - calculated width is not correct
* recalculate sizes when open/close left / right panel, and when browser window resize

**Comment by gabrielkg** [comment]
Resize of viewport following resize of browser window causes mouse-over border around axis, and brush extents, to reflect previous size. See screenshot. Reproducible on Windows, Linux, and both Chrome and Firefox. 
![image](https://user-images.githubusercontent.com/20571319/36234676-76f25ab4-1240-11e8-9ced-5d8da54b810c.png)

**Comment by gabrielkg** [comment]
- Following closing the right panel, thew view is not refreshed;
- After an action that triggers a refresh, right-most axis is drawn outside the view area to the right.

**Comment by gabrielkg** [comment]
Still present in develop commit c6ea70d.
