### ISSUE TITLE
Adding axis to the right of stacked axes draws paths but not new axis

### ISSUE THREAD

**Issue by gabrielkg** [plantinformatics/pretzel#26]
To reproduce: 1) Add 2 datasets. 2) Stack one on top of the other. 3) Add third dataset. The paths will be drawn but the 3rd axis will not be drawn. Adding a 4th dataset works normally. If you stack again and add another, the same behavior occurs.

**Comment by gabrielkg** [comment]
Still present in develop commit c6ea70d.

**Comment by gabrielkg** [comment]
This series of steps still produces a bug in commit 72838ab (split-draw-map2a). Paths are correctly drawn but top stacked axis disappears and last added right axis also disappears.

**Comment by Don-Isdale** [comment]
OK in b5f44af - ready for re-test.
