### ISSUE TITLE
dragging axis, after drop in, can't drop out or drop into another stack

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#31]
dragging axis, after drop in, can't drop out (check xDropOutDistance), also can't drop into another stack.
(commit: 5ce6b2a, in feature/split-draw-map2a)
(tried to add this issue 14 Feb approx 16:00, add was not accepted)

**Comment by Don-Isdale** [comment]
Fixed : [feature/split-draw-map2a 371f693] : Re-connect dragTransitionEnd()

**Comment by gabrielkg** [comment]
Fixed in commit 371f69345db5a1250962086d54d3321db665ff1b.
