### ISSUE TITLE
Display of histograms to handle smaller datasets 

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#373]
#### Description

Configure display of histograms to handle smaller VCF Genotype datasets such as the pulses Raw data.
Initially display histogram or feature tracks when the axis is opened.
Currently data is not displayed until the user zooms in, and they zoom right out the data display is disabled.

Current Display, before zooming in - datasets are not displayed :
![Screenshot from 2024-05-16 14-14-27](https://github.com/plantinformatics/pretzel/assets/2305340/fcd05ccc-61f3-4240-954a-edd23f765ffd)

---

#### Test case
Load Chickpea Raw or Filled-In data on pulses.  Open the axes without zooming in : data should display.   Also confirm that zooming in and out, both with mouse-wheel, brush/Zoom and Reset,  displays data as expected.

##### Expected Test Result :

![Screenshot from 2024-05-13 15-54-57](https://github.com/plantinformatics/pretzel/assets/2305340/62d06f48-bc40-462b-8627-5c9e4ff5983a)

**Comment by kennyAgricultureVic** [comment]
Tested and verified that the changes work
![image](https://github.com/plantinformatics/pretzel/assets/152138829/a0a621b1-1e60-48a4-b8bb-0fd517324b45)

**Comment by kennyAgricultureVic** [comment]
Deployed on https://pulses.plantinformatics.io/
Marking ticket as complete
