### ISSUE TITLE
Working Group Use Case 3 : Request Genotype values for given Dataset, SNP Names, Samples

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#383]
### Sequence of Tasks

1. -  [x] #389
2. - [x] #391
2. - [x] #386
5. - [x] #388
6. - [x] #386  : Revisit this task with the result data to be displayed
7. - [x] #385

The above items are complete, and a preliminary pretzel server version is being set up for test readiness evaluation.
In parallel with this evaluation some minor formatting issues will be completed :

1. - [ ] #392

### Possible extensions

1. - [ ] #384
2. - [ ] #387

**Comment by Don-Isdale** [comment]
Integration Test Plan

The preliminary release of the Pretzel server incorporating the changes for #383 will be available for feedback and test-readiness evaluation.

After the changes are ready for test, the development branch will be tagged with a version _RC (Release Candidate), and the integration tests will be performed.

The integration tests execute the Use Case documented in the User Specification.


---

Test Method :
- Screenshots will be used to record results, and as necessary to highlight discrepancies.
- Variation from desired / expected behaviour will be recorded in github issues, either in comments appended to this issue or issues which reference this issue.


---


Test Preparation :
- login to Pretzel
- refreshing the browser tab or using a new tab will increase repeatability of test results, but it is also relevant to test the new functionality in a Pretzel window which has been used for other work.


---

Test 1 :
- Step through the Use Case documented in the User Specification.
- Expected observations :
- - automatic navigation to the 'Genotype Table' occurs when the user users the 'Genotype Search' panel / dialog, by entering input parameters : dataset Id, Sample names, SNP names.
- - 

Test 2 : white-space in text inputs
- Follow the same process as Test 1, with the inclusion of white space such as extra spaces, tabs, carriage-returns and newlines in the text inputs : Sample Names and Feature (SNP) Names.
In particular, testing on a MS Windows platform copying from a spreadsheet or text viewer may insert CR-LF.
- Expected observations :
- Pretzel should ignore the extra white-space, and produce the same results as before.

Test 3 : input sizes
- Follow the same process as Test 1, with, respectively, small and large text inputs for Sample Names and Feature (SNP) Names.
- Expected observations :
- Pretzel should handle small and reasonably large data inputs,  and produce the correct results.


---

**Comment by gabrielkg** [comment]
The MVP is considered complete, extensions to the basic specification will be continued in #394.

**Comment by Don-Isdale** [comment]
#### Demonstration of MVP



https://github.com/plantinformatics/pretzel/assets/2305340/9f2dd268-5175-4ad6-baed-e2da61393198
