### ISSUE TITLE
Blast returns "The search completed and returned 0 hits" when it fails to run

### ISSUE THREAD

**Issue by kennyAgricultureVic** [plantinformatics/pretzel#398]
Errors are not being passed back to the front end

![Image](https://github.com/plantinformatics/pretzel/assets/20571319/59de5755-6e59-408e-b165-d30fbe778320)

---

#### Introduction

There are 2 concerns here :
- errors in the process of Blast search are causing an empty result.
The error causes were investigated, identified in #401, which records their resolution.

- the errors were logged in the blast server log file, but not propagated to the GUI, which is the focus of this issue.
The goal is to ensure that server configuration errors do not present as empty search results, which is misleading.  By displaying the error message the Pretzel administrators of the system and the data configuration are enabled to solve the error more readily.

---

#### Testing

The errors can be simulated by making one of the Blast database files unreadable, and then performing a DNA Sequence search of that dataset using the Pretzel GUI.
The server log error message will be displayed in the GUI.

**Comment by Don-Isdale** [comment]
#### Deliver errors from blastServer micro-service to web application GUI

The Flask server by default does not deliver error status and error messages on stderr in the reply.
Code will be added to  receive error status and error messages on stderr and convey them in the reply message.

- [ ]  capture error status  and error message from  blastn_cont.bash in  blastServer.py ,  and send them in the reply message.

**Comment by Don-Isdale** [comment]
#### Complete

The listed items for this task are complete and were tested on the test server and then committed.
They will be tested again when that commit is built on the test server, and this issue can be re-opened as necessary.

**Comment by gabrielkg** [comment]
Merged into feature/upgradeFrontend2.
