### ISSUE TITLE
Unpredictable BLAST results on AGG Pretzel

### ISSUE THREAD

**Issue by gabrielkg** [plantinformatics/pretzel#415]
Following the steps to align the WAPO gene against IWGSC_RefSeq_v2.1 on agg.plantinformatics.io, results in unpredictable outcomes. Sometimes the BLAST result is displayed in the table, but nothing is shown in the view. Sometimes the view is updated but only one or two chromosomes have a position marked with a triangle.

![image](https://github.com/user-attachments/assets/63d0a6bb-579a-426f-bcbf-90fac1cfb68e)

**Comment by Don-Isdale** [comment]
####  This issue is resolved

There were no further reports of this issue since the above changes were released.
