### ISSUE TITLE
Collapsing side panels does not trigger redraw

### ISSUE THREAD

**Issue by gabrielkg** [plantinformatics/pretzel#51]
Testing on commit 72838ab (branch split-draw-map2a).

Resizing the browser window triggers a redraw, but collapsing side panels (which also changes size of the draw-map view) does not.

Paths are drawn to old axis position.

Moving an axis triggers redraw which then draws correctly.

**Comment by Don-Isdale** [comment]
Addressed in 8a8d4f4

**Comment by gabrielkg** [comment]
Fixed.
