### ISSUE TITLE
Moving child data loaded into parent axis creates "ghost" axis

### ISSUE THREAD

**Issue by gabrielkg** [plantinformatics/pretzel#52]
Testing on commit 72838ab (branch split-draw-map2a).

Adding a parent axis followed by child successfully loads the data into the same axis. But moving this axis around detaches the axis itself from the point where paths are drawn to. No lines are drawn to the actual parent/child axis, but lines are drawn to the "ghost" axis.

**Comment by Don-Isdale** [comment]
OK in b5f44af - ready for re-test.
