### ISSUE TITLE
"No datasets found!" message persits 

### ISSUE THREAD

**Issue by rsuchecki** [plantinformatics/pretzel#55]
Whole page reload required to get rid of **No datasets found!** message in Explorer. Clicking on local reload button displays loaded datasets but message remains. 

![image](https://user-images.githubusercontent.com/5534231/42618076-12c9cd84-85f3-11e8-8e0c-9d56eaaafcde.png)

**Comment by Gruek** [comment]
Issue fixed after updating mapview to use the left panel code from matrix view. Commit: 9b74a2717d1d53fdeffecdd1b84847212282511f
