### ISSUE TITLE
form to input API endpoint host URL and credentials

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#81]
- started (api-endpoint.hbs,js)
In the MVP this allows input of the token also, so that the user can login to the alternate API connection in a separate browser tab, and paste the authentication token received in the login reply into this token field.

Part of #75

**Comment by Gruek** [comment]
Completed in https://github.com/plantinformatics/pretzel/commit/2c905be70f9c6d9709f62e02c40153aabcebcf76
